var metadata =
[
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPPE",
    "description": "Minimum Information About a Plant Phenotyping Experiment",
    "biological data domain": "phenotypic",
    "link": "https://www.miappe.org/",
    "submission": "",
    "spreadsheet": "YES"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAME",
    "description": "Minimum Information About a Microarray Experiment",
    "biological data domain": "transcriptomic",
    "link": "",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIxS",
    "description": "Minimum Information about a Genome Sequence/ Minimum Information about a Metagenomic Sequence/Sample",
    "biological data domain": "(meta)genomic",
    "link": "https://github.com/GenomicsStandardsConsortium/mixs",
    "submission": "",
    "spreadsheet": "Not to be added- is 'upper level' of other MI lists"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIGSPlant",
    "description": "Minimum information about a genome sequence: Plant",
    "biological data domain": "(meta)genomic",
    "link": "https://genomicsstandardsconsortium.github.io/mixs/MIGSPlant/",
    "submission": "",
    "spreadsheet": "YES"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIGS",
    "description": "** Is now divided into multiple MIGS*** https://genomicsstandardsconsortium.github.io/mixs/#checklists",
    "biological data domain": "(meta)genomic",
    "link": "https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2409278/",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIMS",
    "description": "Metagenome or Environmental (part of MIxS)",
    "biological data domain": "(meta)genomic",
    "link": "https://pubmed.ncbi.nlm.nih.gov/18479204/",
    "submission": "",
    "spreadsheet": "YES"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIMARKSSpecimen",
    "description": "Minimal Information about a Marker Specimen: specimen (part of MIxS)",
    "biological data domain": "(meta)genomic",
    "link": "https://pubmed.ncbi.nlm.nih.gov/21552244/",
    "submission": "",
    "spreadsheet": "YES"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIMARKSSurvey",
    "description": "Minimal Information about a Marker Specimen: survey",
    "biological data domain": "(meta)genomic",
    "link": "",
    "submission": "",
    "spreadsheet": "YES"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE",
    "description": "Minimum Information About a Proteomics Experiment",
    "biological data domain": "proteomic",
    "link": "http://www.psidev.info/miape",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-MS",
    "description": "MIAPE- MS (Mass Spectrometry)",
    "biological data domain": "proteomic",
    "link": "https://www.psidev.info/sites/default/files/2018-03/MIAPE_MS_2.98.pdf",
    "submission": "",
    "spreadsheet": "YES"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-MSI",
    "description": "MIAPE-MSI (Mass Spectrometry Informatics)",
    "biological data domain": "proteomic",
    "link": "https://www.psidev.info/sites/default/files/2018-03/MIAPE_MSI_1.1.pdf",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-Quant",
    "description": "MIAPE-Quant (Mass Spectrometry Quantification)",
    "biological data domain": "proteomic",
    "link": "https://www.psidev.info/sites/default/files/2018-03/MIAPE_Quant_v1.0_Final_0.pdf",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-GE",
    "description": "MIAPE-GE (Gel Electrophoresis)",
    "biological data domain": "proteomic",
    "link": "https://www.psidev.info/sites/default/files/MIAPE_GE_1_4.pdf",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-GI",
    "description": "MIAPE-GI (Gel Informatics)",
    "biological data domain": "proteomic",
    "link": "https://www.psidev.info/sites/default/files/2018-03/miape-gi-v1.pdf",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-CC",
    "description": "MIAPE-CC (Column Chromatography)",
    "biological data domain": "proteomic",
    "link": "https://www.psidev.info/sites/default/files/2018-03/MIAPE_CC_1.1.pdf",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIAPE-CE",
    "description": "MIAPE-CE (Capillary Electrophoresis)",
    "biological data domain": "proteomic",
    "link": "",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIMix",
    "description": "MIMIx (Molecular Interactions)",
    "biological data domain": "proteomic",
    "link": "",
    "submission": "",
    "spreadsheet": ""
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MINSEQE",
    "description": "Minimum Information about a high-throughput SEQuencing Experiment",
    "biological data domain": "transcriptomic",
    "link": "http://fged.org/projects/minseqe/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MISAG",
    "description": "Minimum information about a single amplified genome",
    "biological data domain": "(meta)genomic",
    "link": "https://www.nature.com/articles/nbt.3893",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "MIMAG",
    "description": "Minimum information about metagenome-assembled genome",
    "biological data domain": "(meta)genomic",
    "link": "https://www.nature.com/articles/nbt.3893",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Minimum Information standards",
    "acronym": "Minimum Information about an Uncultivated Virus Genome",
    "description": "MISAG",
    "biological data domain": "(meta)genomic",
    "link": "https://pubmed.ncbi.nlm.nih.gov/30556814/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-MetaboLights",
    "description": "EBI-MetaboLights",
    "biological data domain": "metabolomic",
    "link": "https://www.ebi.ac.uk/metabolights/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-PRIDE",
    "description": "PRoteomics IDEntifications Database",
    "biological data domain": "proteomic",
    "link": "https://www.ebi.ac.uk/pride/",
    "submission": "https://www.ebi.ac.uk/pride/markdownpage/submitdatapage",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "NCBI-BioProject",
    "description": "NCBI-BioProject",
    "biological data domain": "projects",
    "link": "https://www.ncbi.nlm.nih.gov/bioproject/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "NCBI-BioSample",
    "description": "NCBI-BioSample",
    "biological data domain": "samples",
    "link": "https://www.ncbi.nlm.nih.gov/biosample",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "NCBI-GenBank",
    "description": "NCBI-GenBank",
    "biological data domain": "genomic",
    "link": "https://www.ncbi.nlm.nih.gov/genbank/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "NCBI-GEO",
    "description": "Gene Expression Omnibus",
    "biological data domain": "transcriptomic",
    "link": "https://www.ncbi.nlm.nih.gov/geo/",
    "submission": "https://www.ncbi.nlm.nih.gov/geo/info/submission.html",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "NCBI-SRA",
    "description": "Sequence Read Archive",
    "biological data domain": "genomic / transcriptomic sequences",
    "link": "https://www.ncbi.nlm.nih.gov/sra/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "e!DAL-PGP",
    "description": "Plant Genomics & Phenomics Research Data Repository",
    "biological data domain": "phenotypic",
    "link": "https://edal.ipk-gatersleben.de/index.html",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-BioImage Archive",
    "description": "EBI-BioImage Archive",
    "biological data domain": "imaging, microscopy",
    "link": "https://www.ebi.ac.uk/bioimage-archive/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-ArrayExpress",
    "description": "Archive of Functional Genomics Data",
    "biological data domain": "transcriptomic",
    "link": "https://www.ebi.ac.uk/arrayexpress/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-ENA",
    "description": "European Nucleotide Archive",
    "biological data domain": "genomic / transcriptomic sequences",
    "link": "https://www.ebi.ac.uk/ena/",
    "submission": "",
    "spreadsheet": "ERC000011, ERC000020, ERC00035, ERC000037"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-EMPIAR",
    "description": "EBI-EMPIAR",
    "biological data domain": "imaging, microscopy",
    "link": "https://www.ebi.ac.uk/pdbe/emdb/empiar/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-BioModels",
    "description": "EBI-BioModels",
    "biological data domain": "models",
    "link": "https://www.ebi.ac.uk/biomodels/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-BioSamples",
    "description": "EBI-BioSamples",
    "biological data domain": "samples",
    "link": "https://www.ebi.ac.uk/biosamples/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "EBI-BioStudies",
    "description": "EBI-BioStudies",
    "biological data domain": "projects",
    "link": "https://www.ebi.ac.uk/biostudies/",
    "submission": "",
    "spreadsheet": "NO"
  },
  {
    "q1": "Plant",
    "q2": "",
    "type": "Repository",
    "acronym": "Metabolomics Workbench",
    "description": "Metabolomics Workbench",
    "biological data domain": "metabolomic",
    "link": "https://www.metabolomicsworkbench.org/",
    "submission": "",
    "spreadsheet": "NO"
  }
]